export module ISA:Opcodes;

import std;
import :Operands;

export namespace Opcodes {

enum class OPCODE : uint8_t {
    OP_SPECIAL = 0b000000,
    OP_REGIMM  = 0b000001,
    OP_J       = 0b000010,
    OP_JAL     = 0b000011,
    OP_BEQ     = 0b000100,
    OP_BNE     = 0b000101,
    OP_BLEZ    = 0b000110,
    OP_BGTZ    = 0b000111,
    OP_ADDI    = 0b001000,
    OP_ADDIU   = 0b001001,
    OP_SLTI    = 0b001010,
    OP_SLTIU   = 0b001011,
    OP_ANDI    = 0b001100,
    OP_ORI     = 0b001101,
    OP_XORI    = 0b001110,
    OP_LUI     = 0b001111,
    OP_COP0    = 0b010000,
    OP_COP1    = 0b010001,
    OP_COP2    = 0b010010,
    OP_BEQL    = 0b010100,
    OP_BNEL    = 0b010101,
    OP_BLEZL   = 0b010110,
    OP_BGTZL   = 0b010111,
    OP_DADDI   = 0b011000,
    OP_DADDIU  = 0b011001,
    OP_LDL     = 0b011010,
    OP_LDR     = 0b011011,
    OP_LB      = 0b100000,
    OP_LH      = 0b100001,
    OP_LWL     = 0b100010,
    OP_LW      = 0b100011,
    OP_LBU     = 0b100100,
    OP_LHU     = 0b100101,
    OP_LWR     = 0b100110,
    OP_LWU     = 0b100111,
    OP_SB      = 0b101000,
    OP_SH      = 0b101001,
    OP_SWL     = 0b101010,
    OP_SW      = 0b101011,
    OP_SDL     = 0b101100,
    OP_SDR     = 0b101101,
    OP_SWR     = 0b101110,
    OP_CACHE   = 0b101111,
    OP_LL      = 0b110000,
    OP_LWC1    = 0b110001,
    OP_LWC2    = 0b110010,
    OP_LLD     = 0b110100,
    OP_LDC1    = 0b110101,
    OP_LDC2    = 0b110110,
    OP_LD      = 0b110111,
    OP_SC      = 0b111000,
    OP_SWC1    = 0b111001,
    OP_SWC2    = 0b111010,
    OP_SCD     = 0b111100,
    OP_SDC1    = 0b111101,
    OP_SDC2    = 0b111110,
    OP_SD      = 0b111111,
};

enum class SPECIAL : uint8_t {
    OP_SLL     = 0b000000,
    OP_SRL     = 0b000010,
    OP_SRA     = 0b000011,
    OP_SLLV    = 0b000100,
    OP_SRLV    = 0b000110,
    OP_SRAV    = 0b000111,
    OP_JR      = 0b001000,
    OP_JALR    = 0b001001,
    OP_SYSCALL = 0b001100,
    OP_BREAK   = 0b001101,
    OP_SYNC    = 0b001111,
    OP_MFHI    = 0b010000,
    OP_MTHI    = 0b010001,
    OP_MFLO    = 0b010010,
    OP_MTLO    = 0b010011,
    OP_DSLLV   = 0b010100,
    OP_DSRLV   = 0b010110,
    OP_DSRAV   = 0b010111,
    OP_MULT    = 0b011000,
    OP_MULTU   = 0b011001,
    OP_DIV     = 0b011010,
    OP_DIVU    = 0b011011,
    OP_DMULT   = 0b011100,
    OP_DMULTU  = 0b011101,
    OP_DDIV    = 0b011110,
    OP_DDIVU   = 0b011111,
    OP_ADD     = 0b100000,
    OP_ADDU    = 0b100001,
    OP_SUB     = 0b100010,
    OP_SUBU    = 0b100011,
    OP_AND     = 0b100100,
    OP_OR      = 0b100101,
    OP_XOR     = 0b100110,
    OP_NOR     = 0b100111,
    OP_SLT     = 0b101010,
    OP_SLTU    = 0b101011,
    OP_DADD    = 0b101100,
    OP_DADDU   = 0b101101,
    OP_DSUB    = 0b101110,
    OP_DSUBU   = 0b101111,
    OP_TGE     = 0b110000,
    OP_TGEU    = 0b110001,
    OP_TLT     = 0b110010,
    OP_TLTU    = 0b110011,
    OP_TEQ     = 0b110100,
    OP_TNE     = 0b110110,
    OP_DSLL    = 0b111000,
    OP_DSRL    = 0b111010,
    OP_DSRA    = 0b111011,
    OP_DSLL32  = 0b111100,
    OP_DSRL32  = 0b111110,
    OP_DSRA32  = 0b111111,
};

enum class REGIMM_rt : uint8_t {
    OP_BLTZ    = 0b000000,
    OP_BGEZ    = 0b000001,
    OP_BLTZL   = 0b000010,
    OP_BGEZL   = 0b000011,
    OP_TGEI    = 0b001000,
    OP_TGEIU   = 0b001001,
    OP_TLTI    = 0b001010,
    OP_TLTIU   = 0b001011,
    OP_TEQI    = 0b001100,
    OP_TNEI    = 0b001110,
    OP_BLTZAL  = 0b010000,
    OP_BGEZAL  = 0b010001,
    OP_BLTZALL = 0b010010,
    OP_BGEZALL = 0b010011,
};

// two high bits = 'z' (coprocessor number)
enum class COPz_rs : uint8_t {
    OP_MFCz  = 0b00000,
    OP_DMFCz = 0b00001,
    OP_CFCz  = 0b00010,
    OP_MTCz  = 0b00100,
    OP_DMTCz = 0b00101,
    OP_CTCz  = 0b00110,
    OP_BC    = 0b01000,
    // OP_COPz = 0b1xxxx, handled specially
};

enum class COPz_rt : uint8_t {
    OP_BCzF  = 0b00000,
    OP_BCzT  = 0b00001,
    OP_BCzFL = 0b00010,
    OP_BCzTL = 0b00100,
};

enum class CP0 : uint8_t {
    OP_TLBR  = 0b000001,
    OP_TLBWI = 0b000010,
    OP_TLBWR = 0b000110,
    OP_TLBP  = 0b001000,
    OP_ERET  = 0b011000,
};

enum class COP2_LOAD : uint8_t {
    OP_LBV = 0b0000,
    OP_LSV = 0b0001,
    OP_LLV = 0b0010,
    OP_LDV = 0b0011,
    OP_LQV = 0b0100,
    OP_LRV = 0b0101,
    OP_LPV = 0b0110,
    OP_LUV = 0b0111,
    OP_LHV = 0b1000,
    OP_LFV = 0b1001,
    OP_LWV = 0b1010,
    OP_LTV = 0b1011,
};

enum class COP2_STORE : uint8_t {
    OP_SBV = 0b0000,
    OP_SSV = 0b0001,
    OP_SLV = 0b0010,
    OP_SDV = 0b0011,
    OP_SQV = 0b0100,
    OP_SRV = 0b0101,
    OP_SPV = 0b0110,
    OP_SUV = 0b0111,
    OP_SHV = 0b1000,
    OP_SFV = 0b1001,
    OP_SWV = 0b1010,
    OP_STV = 0b1011,
};

enum class COP2_VECTOR : uint8_t {
    OP_VMULF        = 0b000000,
    OP_VMULU        = 0b000001,
    OP_VRNDP        = 0b000010,
    OP_VMULQ        = 0b000011,
    OP_VMUDL        = 0b000100,
    OP_VMUDM        = 0b000101,
    OP_VMUDN        = 0b000110,
    OP_VMUDH        = 0b000111,
    OP_VMACF        = 0b001000,
    OP_VMACU        = 0b001001,
    OP_VRNDN        = 0b001010,
    OP_VMACQ        = 0b001011,
    OP_VMADL        = 0b001100,
    OP_VMADM        = 0b001101,
    OP_VMADN        = 0b001110,
    OP_VMADH        = 0b001111,
    OP_VADD         = 0b010000,
    OP_VSUB         = 0b010001,
    OP_VSUT         = 0b010010,
    OP_VABS         = 0b010011,
    OP_VADDC        = 0b010100,
    OP_VSUBC        = 0b010101,
    OP_VADDB        = 0b010110,
    OP_VSUBB        = 0b010111,
    OP_VACCB        = 0b011000,
    OP_VSUCB        = 0b011001,
    OP_VSAD         = 0b011010,
    OP_VSAC         = 0b011011,
    OP_VSUM         = 0b011100,
    OP_VSAW         = 0b011101,
    OP_RESERVED_V0  = 0b011110,
    OP_RESERVED_V1  = 0b011111,
    OP_VLT          = 0b100000,
    OP_VEQ          = 0b100001,
    OP_VNE          = 0b100010,
    OP_VGE          = 0b100011,
    OP_VCL          = 0b100100,
    OP_VCH          = 0b100101,
    OP_VCR          = 0b100110,
    OP_VMRG         = 0b100111,
    OP_VAND         = 0b101000,
    OP_VNAND        = 0b101001,
    OP_VOR          = 0b101010,
    OP_VNOR         = 0b101011,
    OP_VXOR         = 0b101100,
    OP_VNXOR        = 0b101101,
    OP_RESERVED_V2  = 0b101110,
    OP_RESERVED_V3  = 0b101111,
    OP_VRCP         = 0b110000,
    OP_VRCPL        = 0b110001,
    OP_VRCPH        = 0b110010,
    OP_VMOV         = 0b110011,
    OP_VRSQ         = 0b110100,
    OP_VRSQL        = 0b110101,
    OP_VRSQH        = 0b110110,
    OP_VNOP         = 0b110111,
    OP_RESERVED_V4  = 0b111000,
    OP_RESERVED_V5  = 0b111001,
    OP_RESERVED_V6  = 0b111010,
    OP_RESERVED_V7  = 0b111011,
    OP_RESERVED_V8  = 0b111100,
    OP_RESERVED_V9  = 0b111101,
    OP_RESERVED_V10 = 0b111110,
    OP_VNULL        = 0b111111,
};

struct UnifiedOpcodeBase {
    enum : uint32_t {
        INVALID          = 0,
        OPCODE_BASE      = 0x100,
        SPECIAL_BASE     = 0x200,
        REGIMM_rt_BASE   = 0x300,
        COPz_rs_BASE     = 0x400,
        COPz_rt_BASE     = 0x500,
        CP0_BASE         = 0x600,
        COP2_LOAD_BASE   = 0x700,
        COP2_STORE_BASE  = 0x800,
        COP2_SCALAR_BASE = 0x900,
        COP2_VECTOR_BASE = 0xA00,
    };
};

enum class UnifiedOpcode : uint32_t {
    // clang-format off
        OP_UNKNOWN = static_cast<uint32_t>(UnifiedOpcodeBase::INVALID),
        OP_NOP,
        OP_COPz,
        // Standard opcodes
        OP_SPECIAL = static_cast<uint32_t>(UnifiedOpcodeBase::OPCODE_BASE),
        OP_REGIMM,
        OP_J        [[=^^ISA::OpType::Jump]],
        OP_JAL      [[=^^ISA::OpType::Jump]],
        OP_BEQ      [[=^^ISA::OpType::Branch2]],
        OP_BNE      [[=^^ISA::OpType::Branch2]],
        OP_BLEZ     [[=^^ISA::OpType::Branch1]],
        OP_BGTZ     [[=^^ISA::OpType::Branch1]],
        OP_ADDI     [[=^^ISA::OpType::AluImm]],
        OP_ADDIU    [[=^^ISA::OpType::AluImm]],
        OP_SLTI     [[=^^ISA::OpType::AluImm]],
        OP_SLTIU    [[=^^ISA::OpType::AluImm]],
        OP_ANDI     [[=^^ISA::OpType::AluImm]],
        OP_ORI      [[=^^ISA::OpType::AluImm]],
        OP_XORI     [[=^^ISA::OpType::AluImm]],
        OP_LUI      [[=^^ISA::OpType::AluImmLoad]],
        OP_COP0,
        OP_COP1,
        OP_COP2,
        OP_RESERVED_1,
        OP_BEQL     [[=^^ISA::OpType::Branch2]],
        OP_BNEL     [[=^^ISA::OpType::Branch2]],
        OP_BLEZL    [[=^^ISA::OpType::Branch2]],
        OP_BGTZL    [[=^^ISA::OpType::Branch2]],
        OP_DADDI    [[=^^ISA::OpType::AluImm]],
        OP_DADDIU   [[=^^ISA::OpType::AluImm]],
        OP_LDL      [[=^^ISA::OpType::LoadStore]],
        OP_LDR      [[=^^ISA::OpType::LoadStore]],
        OP_RESERVED_2,
        OP_RESERVED_3,
        OP_RESERVED_4,
        OP_RESERVED_5,
        OP_LB       [[=^^ISA::OpType::LoadStore]],
        OP_LH       [[=^^ISA::OpType::LoadStore]],
        OP_LWL      [[=^^ISA::OpType::LoadStore]],
        OP_LW       [[=^^ISA::OpType::LoadStore]],
        OP_LBU      [[=^^ISA::OpType::LoadStore]],
        OP_LHU      [[=^^ISA::OpType::LoadStore]],
        OP_LWR      [[=^^ISA::OpType::LoadStore]],
        OP_LWU      [[=^^ISA::OpType::LoadStore]],
        OP_SB       [[=^^ISA::OpType::LoadStore]],
        OP_SH       [[=^^ISA::OpType::LoadStore]],
        OP_SWL      [[=^^ISA::OpType::LoadStore]],
        OP_SW       [[=^^ISA::OpType::LoadStore]],
        OP_SDL      [[=^^ISA::OpType::LoadStore]],
        OP_SDR      [[=^^ISA::OpType::LoadStore]],
        OP_SWR      [[=^^ISA::OpType::LoadStore]],
        OP_CACHE    [[=^^ISA::OpType::LoadStore]],
        OP_LL       [[=^^ISA::OpType::LoadStore]],
        OP_LWC1,
        OP_LWC2,
        OP_RESERVED_6,
        OP_LLD      [[=^^ISA::OpType::LoadStore]],
        OP_LDC1,
        OP_LDC2,
        OP_LD       [[=^^ISA::OpType::LoadStore]],
        OP_SC       [[=^^ISA::OpType::LoadStore]],
        OP_SWC1,
        OP_SWC2,
        OP_RESERVED_7,
        OP_SCD      [[=^^ISA::OpType::LoadStore]],
        OP_SDC1,
        OP_SDC2,
        OP_SD       [[=^^ISA::OpType::LoadStore]],
        // SPECIAL opcodes
        OP_SLL      [[=^^ISA::OpType::Shift]] = static_cast<uint32_t>(UnifiedOpcodeBase::SPECIAL_BASE),
        OP_RESERVED_8,
        OP_SRL      [[=^^ISA::OpType::Shift]],
        OP_SRA      [[=^^ISA::OpType::Shift]],
        OP_SLLV     [[=^^ISA::OpType::ShiftVar]],
        OP_RESERVED_9,
        OP_SRLV     [[=^^ISA::OpType::ShiftVar]],
        OP_SRAV     [[=^^ISA::OpType::ShiftVar]],
        OP_JR       [[=^^ISA::OpType::JumpReg]],
        OP_JALR     [[=^^ISA::OpType::JumpLinkReg]],
        OP_RESERVED_10,
        OP_RESERVED_11,
        OP_SYSCALL  [[=^^ISA::OpType::Special]],
        OP_BREAK    [[=^^ISA::OpType::Special]],
        OP_RESERVED_12,
        OP_SYNC     [[=^^ISA::OpType::Special]],
        OP_MFHI     [[=^^ISA::OpType::MoveFrom]],
        OP_MTHI     [[=^^ISA::OpType::MoveTo]],
        OP_MFLO     [[=^^ISA::OpType::MoveFrom]],
        OP_MTLO     [[=^^ISA::OpType::MoveTo]],
        OP_DSLLV    [[=^^ISA::OpType::ShiftVar]],
        OP_RESERVED_13,
        OP_DSRLV    [[=^^ISA::OpType::ShiftVar]],
        OP_DSRAV    [[=^^ISA::OpType::ShiftVar]],
        OP_MULT     [[=^^ISA::OpType::MulDiv]],
        OP_MULTU    [[=^^ISA::OpType::MulDiv]],
        OP_DIV      [[=^^ISA::OpType::MulDiv]],
        OP_DIVU     [[=^^ISA::OpType::MulDiv]],
        OP_DMULT    [[=^^ISA::OpType::MulDiv]],
        OP_DMULTU   [[=^^ISA::OpType::MulDiv]],
        OP_DDIV     [[=^^ISA::OpType::MulDiv]],
        OP_DDIVU    [[=^^ISA::OpType::MulDiv]],
        OP_ADD      [[=^^ISA::OpType::ThreeOp]],
        OP_ADDU     [[=^^ISA::OpType::ThreeOp]],
        OP_SUB      [[=^^ISA::OpType::ThreeOp]],
        OP_SUBU     [[=^^ISA::OpType::ThreeOp]],
        OP_AND      [[=^^ISA::OpType::ThreeOp]],
        OP_OR       [[=^^ISA::OpType::ThreeOp]],
        OP_XOR      [[=^^ISA::OpType::ThreeOp]],
        OP_NOR      [[=^^ISA::OpType::ThreeOp]],
        OP_RESERVED_14,
        OP_RESERVED_15,
        OP_SLT      [[=^^ISA::OpType::ThreeOp]],
        OP_SLTU     [[=^^ISA::OpType::ThreeOp]],
        OP_DADD     [[=^^ISA::OpType::ThreeOp]],
        OP_DADDU    [[=^^ISA::OpType::ThreeOp]],
        OP_DSUB     [[=^^ISA::OpType::ThreeOp]],
        OP_DSUBU    [[=^^ISA::OpType::ThreeOp]],
        OP_TGE      [[=^^ISA::OpType::Trap]],
        OP_TGEU     [[=^^ISA::OpType::Trap]],
        OP_TLT      [[=^^ISA::OpType::Trap]],
        OP_TLTU     [[=^^ISA::OpType::Trap]],
        OP_TEQ      [[=^^ISA::OpType::Trap]],
        OP_RESERVED_16,
        OP_TNE      [[=^^ISA::OpType::Trap]],
        OP_RESERVED_17,
        OP_DSLL     [[=^^ISA::OpType::Shift]],
        OP_RESERVED_18,
        OP_DSRL     [[=^^ISA::OpType::Shift]],
        OP_DSRA     [[=^^ISA::OpType::Shift]],
        OP_DSLL32   [[=^^ISA::OpType::Shift]],
        OP_RESERVED_19,
        OP_DSRL32   [[=^^ISA::OpType::Shift]],
        OP_DSRA32   [[=^^ISA::OpType::Shift]],
        // REGIMM opcodes
        OP_BLTZ     [[=^^ISA::OpType::Branch1]] = static_cast<uint32_t>(UnifiedOpcodeBase::REGIMM_rt_BASE),
        OP_BGEZ     [[=^^ISA::OpType::Branch1]],
        OP_BLTZL    [[=^^ISA::OpType::Branch1]],
        OP_BGEZL    [[=^^ISA::OpType::Branch1]],
        OP_RESERVED_20,
        OP_RESERVED_21,
        OP_RESERVED_22,
        OP_RESERVED_23,
        OP_TGEI     [[=^^ISA::OpType::TrapImm]],
        OP_TGEIU    [[=^^ISA::OpType::TrapImm]],
        OP_TLTI     [[=^^ISA::OpType::TrapImm]],
        OP_TLTIU    [[=^^ISA::OpType::TrapImm]],
        OP_TEQI     [[=^^ISA::OpType::TrapImm]],
        OP_RESERVED_24,
        OP_TNEI     [[=^^ISA::OpType::TrapImm]],
        OP_RESERVED_25,
        OP_BLTZAL   [[=^^ISA::OpType::Branch1]],
        OP_BGEZAL   [[=^^ISA::OpType::Branch1]],
        OP_BLTZALL  [[=^^ISA::OpType::Branch1]],
        OP_BGEZALL  [[=^^ISA::OpType::Branch1]],
        // COPz RS opcodes
        OP_MFCz     [[=^^ISA::OpType::CP0Move]] = static_cast<uint32_t>(UnifiedOpcodeBase::COPz_rs_BASE),
        OP_DMFCz    [[=^^ISA::OpType::CP0Move]],
        OP_CFCz     [[=^^ISA::OpType::CP0Move]],
        OP_RESERVED_26,
        OP_MTCz     [[=^^ISA::OpType::CP0Move]],
        OP_DMTCz    [[=^^ISA::OpType::CP0Move]],
        OP_CTCz     [[=^^ISA::OpType::CP0Move]],
        OP_RESERVED_27,
        OP_BC       [[=^^ISA::OpType::CP0Move]],
        // COPz RT opcodes
        OP_BCzF     [[=^^ISA::OpType::TypeI_Imm]] = static_cast<uint32_t>(UnifiedOpcodeBase::COPz_rt_BASE),
        OP_BCzT     [[=^^ISA::OpType::TypeI_Imm]],
        OP_BCzFL    [[=^^ISA::OpType::TypeI_Imm]],
        OP_BCzTL    [[=^^ISA::OpType::TypeI_Imm]],
        // CP0 opcodes
        OP_RESERVED_28 = static_cast<uint32_t>(UnifiedOpcodeBase::CP0_BASE),
        OP_TLBR,
        OP_TLBWI,
        OP_RESERVED_29,
        OP_RESERVED_30,
        OP_RESERVED_31,
        OP_TLBWR,
        OP_RESERVED_32,
        OP_TLBP,
        OP_RESERVED_33,
        OP_RESERVED_34,
        OP_RESERVED_35,
        OP_RESERVED_36,
        OP_RESERVED_37,
        OP_RESERVED_38,
        OP_RESERVED_39,
        OP_RESERVED_40,
        OP_RESERVED_41,
        OP_RESERVED_42,
        OP_RESERVED_43,
        OP_RESERVED_44,
        OP_RESERVED_45,
        OP_RESERVED_46,
        OP_RESERVED_47,
        OP_ERET,
        // COP2 (RSP) opcodes
        OP_LBV [[=^^ISA::OpType::VecLoadStore]] = static_cast<uint32_t>(UnifiedOpcodeBase::COP2_LOAD_BASE),
        OP_LSV [[=^^ISA::OpType::VecLoadStore]],
        OP_LLV [[=^^ISA::OpType::VecLoadStore]],
        OP_LDV [[=^^ISA::OpType::VecLoadStore]],
        OP_LQV [[=^^ISA::OpType::VecLoadStore]],
        OP_LRV [[=^^ISA::OpType::VecLoadStore]],
        OP_LPV [[=^^ISA::OpType::VecLoadStore]],
        OP_LUV [[=^^ISA::OpType::VecLoadStore]],
        OP_LHV [[=^^ISA::OpType::VecLoadStore]],
        OP_LFV [[=^^ISA::OpType::VecLoadStore]],
        OP_LWV [[=^^ISA::OpType::VecLoadStore]],
        OP_LTV [[=^^ISA::OpType::VecLoadStore]],
        OP_SBV [[=^^ISA::OpType::VecLoadStore]] = static_cast<uint32_t>(UnifiedOpcodeBase::COP2_STORE_BASE),
        OP_SSV [[=^^ISA::OpType::VecLoadStore]],
        OP_SLV [[=^^ISA::OpType::VecLoadStore]],
        OP_SDV [[=^^ISA::OpType::VecLoadStore]],
        OP_SQV [[=^^ISA::OpType::VecLoadStore]],
        OP_SRV [[=^^ISA::OpType::VecLoadStore]],
        OP_SPV [[=^^ISA::OpType::VecLoadStore]],
        OP_SUV [[=^^ISA::OpType::VecLoadStore]],
        OP_SHV [[=^^ISA::OpType::VecLoadStore]],
        OP_SFV [[=^^ISA::OpType::VecLoadStore]],
        OP_SWV [[=^^ISA::OpType::VecLoadStore]],
        OP_STV [[=^^ISA::OpType::VecLoadStore]],
        OP_VMULF  [[=^^ISA::OpType::VecAlu]] = static_cast<uint32_t>(UnifiedOpcodeBase::COP2_VECTOR_BASE),
        OP_VMULU  [[=^^ISA::OpType::VecAlu]],
        OP_VRNDP  [[=^^ISA::OpType::VecAlu]],
        OP_VMULQ  [[=^^ISA::OpType::VecAlu]],
        OP_VMUDL  [[=^^ISA::OpType::VecAlu]],
        OP_VMUDM  [[=^^ISA::OpType::VecAlu]],
        OP_VMUDN  [[=^^ISA::OpType::VecAlu]],
        OP_VMUDH  [[=^^ISA::OpType::VecAlu]],
        OP_VMACF  [[=^^ISA::OpType::VecAlu]],
        OP_VMACU  [[=^^ISA::OpType::VecAlu]],
        OP_VRNDN  [[=^^ISA::OpType::VecAlu]],
        OP_VMACQ  [[=^^ISA::OpType::VecAlu]],
        OP_VMADL  [[=^^ISA::OpType::VecAlu]],
        OP_VMADM  [[=^^ISA::OpType::VecAlu]],
        OP_VMADN  [[=^^ISA::OpType::VecAlu]],
        OP_VMADH  [[=^^ISA::OpType::VecAlu]],
        OP_VADD   [[=^^ISA::OpType::VecAlu]],
        OP_VSUB   [[=^^ISA::OpType::VecAlu]],
        OP_VSUT   [[=^^ISA::OpType::VecAlu]],
        OP_VABS   [[=^^ISA::OpType::VecAlu]],
        OP_VADDC  [[=^^ISA::OpType::VecAlu]],
        OP_VSUBC  [[=^^ISA::OpType::VecAlu]],
        OP_VADDB  [[=^^ISA::OpType::VecAlu]],
        OP_VSUBB  [[=^^ISA::OpType::VecAlu]],
        OP_VACCB  [[=^^ISA::OpType::VecAlu]],
        OP_VSUCB  [[=^^ISA::OpType::VecAlu]],
        OP_VSAD   [[=^^ISA::OpType::VecAlu]],
        OP_VSAC   [[=^^ISA::OpType::VecAlu]],
        OP_VSUM   [[=^^ISA::OpType::VecAlu]],
        OP_VSAW   [[=^^ISA::OpType::VecAlu]],
        OP_RESERVED_V0,
        OP_RESERVED_V1,
        OP_VLT    [[=^^ISA::OpType::VecAlu]],
        OP_VEQ    [[=^^ISA::OpType::VecAlu]],
        OP_VNE    [[=^^ISA::OpType::VecAlu]],
        OP_VGE    [[=^^ISA::OpType::VecAlu]],
        OP_VCL    [[=^^ISA::OpType::VecAlu]],
        OP_VCH    [[=^^ISA::OpType::VecAlu]],
        OP_VCR    [[=^^ISA::OpType::VecAlu]],
        OP_VMRG   [[=^^ISA::OpType::VecAlu]],
        OP_VAND   [[=^^ISA::OpType::VecAlu]],
        OP_VNAND  [[=^^ISA::OpType::VecAlu]],
        OP_VOR    [[=^^ISA::OpType::VecAlu]],
        OP_VNOR   [[=^^ISA::OpType::VecAlu]],
        OP_VXOR   [[=^^ISA::OpType::VecAlu]],
        OP_VNXOR  [[=^^ISA::OpType::VecAlu]],
        OP_RESERVED_V2,
        OP_RESERVED_V3,
        OP_VRCP   [[=^^ISA::OpType::VecSingleLane]],
        OP_VRCPL  [[=^^ISA::OpType::VecSingleLane]],
        OP_VRCPH  [[=^^ISA::OpType::VecSingleLane]],
        OP_VMOV   [[=^^ISA::OpType::VecSingleLane]],
        OP_VRSQ   [[=^^ISA::OpType::VecSingleLane]],
        OP_VRSQL  [[=^^ISA::OpType::VecSingleLane]],
        OP_VRSQH  [[=^^ISA::OpType::VecSingleLane]],
        OP_VNOP,
        OP_RESERVED_V4,
        OP_RESERVED_V5,
        OP_RESERVED_V6,
        OP_RESERVED_V7,
        OP_RESERVED_V8,
        OP_RESERVED_V9,
        OP_RESERVED_V10,
        OP_VNULL,
    // clang-format on
};

} // namespace Opcodes
