export module ISA:Opcodes;

import std;
import :Operands;

export namespace Opcodes {

enum class OPCODE : uint8_t {
    OP_SPECIAL = 0b000000,
    OP_REGIMM  = 0b000001,
    OP_J       = 0b000010,
    OP_JAL     = 0b000011,
    OP_BEQ     = 0b000100,
    OP_BNE     = 0b000101,
    OP_BLEZ    = 0b000110,
    OP_BGTZ    = 0b000111,
    OP_ADDI    = 0b001000,
    OP_ADDIU   = 0b001001,
    OP_SLTI    = 0b001010,
    OP_SLTIU   = 0b001011,
    OP_ANDI    = 0b001100,
    OP_ORI     = 0b001101,
    OP_XORI    = 0b001110,
    OP_LUI     = 0b001111,
    OP_COP0    = 0b010000,
    OP_COP1    = 0b010001,
    OP_COP2    = 0b010010,
    OP_BEQL    = 0b010100,
    OP_BNEL    = 0b010101,
    OP_BLEZL   = 0b010110,
    OP_BGTZL   = 0b010111,
    OP_DADDI   = 0b011000,
    OP_DADDIU  = 0b011001,
    OP_LDL     = 0b011010,
    OP_LDR     = 0b011011,
    OP_LB      = 0b100000,
    OP_LH      = 0b100001,
    OP_LWL     = 0b100010,
    OP_LW      = 0b100011,
    OP_LBU     = 0b100100,
    OP_LHU     = 0b100101,
    OP_LWR     = 0b100110,
    OP_LWU     = 0b100111,
    OP_SB      = 0b101000,
    OP_SH      = 0b101001,
    OP_SWL     = 0b101010,
    OP_SW      = 0b101011,
    OP_SDL     = 0b101100,
    OP_SDR     = 0b101101,
    OP_SWR     = 0b101110,
    OP_CACHE   = 0b101111,
    OP_LL      = 0b110000,
    OP_LWC1    = 0b110001,
    OP_LWC2    = 0b110010,
    OP_LLD     = 0b110100,
    OP_LDC1    = 0b110101,
    OP_LDC2    = 0b110110,
    OP_LD      = 0b110111,
    OP_SC      = 0b111000,
    OP_SWC1    = 0b111001,
    OP_SWC2    = 0b111010,
    OP_SCD     = 0b111100,
    OP_SDC1    = 0b111101,
    OP_SDC2    = 0b111110,
    OP_SD      = 0b111111,
};

enum class SPECIAL : uint8_t {
    OP_SLL     = 0b000000,
    OP_SRL     = 0b000010,
    OP_SRA     = 0b000011,
    OP_SLLV    = 0b000100,
    OP_SRLV    = 0b000110,
    OP_SRAV    = 0b000111,
    OP_JR      = 0b001000,
    OP_JALR    = 0b001001,
    OP_SYSCALL = 0b001100,
    OP_BREAK   = 0b001101,
    OP_SYNC    = 0b001111,
    OP_MFHI    = 0b010000,
    OP_MTHI    = 0b010001,
    OP_MFLO    = 0b010010,
    OP_MTLO    = 0b010011,
    OP_DSLLV   = 0b010100,
    OP_DSRLV   = 0b010110,
    OP_DSRAV   = 0b010111,
    OP_MULT    = 0b011000,
    OP_MULTU   = 0b011001,
    OP_DIV     = 0b011010,
    OP_DIVU    = 0b011011,
    OP_DMULT   = 0b011100,
    OP_DMULTU  = 0b011101,
    OP_DDIV    = 0b011110,
    OP_DDIVU   = 0b011111,
    OP_ADD     = 0b100000,
    OP_ADDU    = 0b100001,
    OP_SUB     = 0b100010,
    OP_SUBU    = 0b100011,
    OP_AND     = 0b100100,
    OP_OR      = 0b100101,
    OP_XOR     = 0b100110,
    OP_NOR     = 0b100111,
    OP_SLT     = 0b101010,
    OP_SLTU    = 0b101011,
    OP_DADD    = 0b101100,
    OP_DADDU   = 0b101101,
    OP_DSUB    = 0b101110,
    OP_DSUBU   = 0b101111,
    OP_TGE     = 0b110000,
    OP_TGEU    = 0b110001,
    OP_TLT     = 0b110010,
    OP_TLTU    = 0b110011,
    OP_TEQ     = 0b110100,
    OP_TNE     = 0b110110,
    OP_DSLL    = 0b111000,
    OP_DSRL    = 0b111010,
    OP_DSRA    = 0b111011,
    OP_DSLL32  = 0b111100,
    OP_DSRL32  = 0b111110,
    OP_DSRA32  = 0b111111,
};

enum class REGIMM_rt : uint8_t {
    OP_BLTZ    = 0b000000,
    OP_BGEZ    = 0b000001,
    OP_BLTZL   = 0b000010,
    OP_BGEZL   = 0b000011,
    OP_TGEI    = 0b001000,
    OP_TGEIU   = 0b001001,
    OP_TLTI    = 0b001010,
    OP_TLTIU   = 0b001011,
    OP_TEQI    = 0b001100,
    OP_TNEI    = 0b001110,
    OP_BLTZAL  = 0b010000,
    OP_BGEZAL  = 0b010001,
    OP_BLTZALL = 0b010010,
    OP_BGEZALL = 0b010011,
};

// two high bits = 'z' (coprocessor number)
enum class COPz_rs : uint8_t {
    OP_MFCz  = 0b00000,
    OP_DMFCz = 0b00001,
    OP_CFCz  = 0b00010,
    OP_MTCz  = 0b00100,
    OP_DMTCz = 0b00101,
    OP_CTCz  = 0b00110,
    OP_BC    = 0b01000,
    // OP_COPz = 0b1xxxx, handled specially
};

enum class COPz_rt : uint8_t {
    OP_BCzF  = 0b00000,
    OP_BCzT  = 0b00001,
    OP_BCzFL = 0b00010,
    OP_BCzTL = 0b00100,
};

enum class CP0 : uint8_t {
    OP_TLBR  = 0b000001,
    OP_TLBWI = 0b000010,
    OP_TLBWR = 0b000110,
    OP_TLBP  = 0b001000,
    OP_ERET  = 0b011000,
};

struct UnifiedOpcodeBase {
    enum : uint32_t {
        INVALID        = 0,
        OPCODE_BASE    = 0x100,
        SPECIAL_BASE   = 0x200,
        REGIMM_rt_BASE = 0x300,
        COPz_rs_BASE   = 0x400,
        COPz_rt_BASE   = 0x500,
        CP0_BASE       = 0x600,
    };
};

enum class UnifiedOpcode : uint32_t {
    // clang-format off
        OP_UNKNOWN = static_cast<uint32_t>(UnifiedOpcodeBase::INVALID),
        OP_NOP,
        OP_COPz,
        // Standard opcodes
        OP_SPECIAL = static_cast<uint32_t>(UnifiedOpcodeBase::OPCODE_BASE),
        OP_REGIMM,
        OP_J        [[=^^ISA::CPUOpType::Jump]],
        OP_JAL      [[=^^ISA::CPUOpType::Jump]],
        OP_BEQ      [[=^^ISA::CPUOpType::Branch2]],
        OP_BNE      [[=^^ISA::CPUOpType::Branch2]],
        OP_BLEZ     [[=^^ISA::CPUOpType::Branch1]],
        OP_BGTZ     [[=^^ISA::CPUOpType::Branch1]],
        OP_ADDI     [[=^^ISA::CPUOpType::AluImm]],
        OP_ADDIU    [[=^^ISA::CPUOpType::AluImm]],
        OP_SLTI     [[=^^ISA::CPUOpType::AluImm]],
        OP_SLTIU    [[=^^ISA::CPUOpType::AluImm]],
        OP_ANDI     [[=^^ISA::CPUOpType::AluImm]],
        OP_ORI      [[=^^ISA::CPUOpType::AluImm]],
        OP_XORI     [[=^^ISA::CPUOpType::AluImm]],
        OP_LUI      [[=^^ISA::CPUOpType::AluImmLoad]],
        OP_COP0,
        OP_COP1,
        OP_COP2,
        OP_RESERVED_1,
        OP_BEQL     [[=^^ISA::CPUOpType::Branch2]],
        OP_BNEL     [[=^^ISA::CPUOpType::Branch2]],
        OP_BLEZL    [[=^^ISA::CPUOpType::Branch2]],
        OP_BGTZL    [[=^^ISA::CPUOpType::Branch2]],
        OP_DADDI    [[=^^ISA::CPUOpType::AluImm]],
        OP_DADDIU   [[=^^ISA::CPUOpType::AluImm]],
        OP_LDL      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LDR      [[=^^ISA::CPUOpType::LoadStore]],
        OP_RESERVED_2,
        OP_RESERVED_3,
        OP_RESERVED_4,
        OP_RESERVED_5,
        OP_LB       [[=^^ISA::CPUOpType::LoadStore]],
        OP_LH       [[=^^ISA::CPUOpType::LoadStore]],
        OP_LWL      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LW       [[=^^ISA::CPUOpType::LoadStore]],
        OP_LBU      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LHU      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LWR      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LWU      [[=^^ISA::CPUOpType::LoadStore]],
        OP_SB       [[=^^ISA::CPUOpType::LoadStore]],
        OP_SH       [[=^^ISA::CPUOpType::LoadStore]],
        OP_SWL      [[=^^ISA::CPUOpType::LoadStore]],
        OP_SW       [[=^^ISA::CPUOpType::LoadStore]],
        OP_SDL      [[=^^ISA::CPUOpType::LoadStore]],
        OP_SDR      [[=^^ISA::CPUOpType::LoadStore]],
        OP_SWR      [[=^^ISA::CPUOpType::LoadStore]],
        OP_CACHE    [[=^^ISA::CPUOpType::LoadStore]],
        OP_LL       [[=^^ISA::CPUOpType::LoadStore]],
        OP_LWC1,
        OP_LWC2,
        OP_RESERVED_6,
        OP_LLD      [[=^^ISA::CPUOpType::LoadStore]],
        OP_LDC1,
        OP_LDC2,
        OP_LD       [[=^^ISA::CPUOpType::LoadStore]],
        OP_SC       [[=^^ISA::CPUOpType::LoadStore]],
        OP_SWC1,
        OP_SWC2,
        OP_RESERVED_7,
        OP_SCD      [[=^^ISA::CPUOpType::LoadStore]],
        OP_SDC1,
        OP_SDC2,
        OP_SD       [[=^^ISA::CPUOpType::LoadStore]],
        // SPECIAL opcodes
        OP_SLL      [[=^^ISA::CPUOpType::Shift]] = static_cast<uint32_t>(UnifiedOpcodeBase::SPECIAL_BASE),
        OP_RESERVED_8,
        OP_SRL      [[=^^ISA::CPUOpType::Shift]],
        OP_SRA      [[=^^ISA::CPUOpType::Shift]],
        OP_SLLV     [[=^^ISA::CPUOpType::ShiftVar]],
        OP_RESERVED_9,
        OP_SRLV     [[=^^ISA::CPUOpType::ShiftVar]],
        OP_SRAV     [[=^^ISA::CPUOpType::ShiftVar]],
        OP_JR       [[=^^ISA::CPUOpType::JumpReg]],
        OP_JALR     [[=^^ISA::CPUOpType::JumpLinkReg]],
        OP_RESERVED_10,
        OP_RESERVED_11,
        OP_SYSCALL  [[=^^ISA::CPUOpType::Special]],
        OP_BREAK    [[=^^ISA::CPUOpType::Special]],
        OP_RESERVED_12,
        OP_SYNC     [[=^^ISA::CPUOpType::Special]],
        OP_MFHI     [[=^^ISA::CPUOpType::MoveFrom]],
        OP_MTHI     [[=^^ISA::CPUOpType::MoveTo]],
        OP_MFLO     [[=^^ISA::CPUOpType::MoveFrom]],
        OP_MTLO     [[=^^ISA::CPUOpType::MoveTo]],
        OP_DSLLV    [[=^^ISA::CPUOpType::ShiftVar]],
        OP_RESERVED_13,
        OP_DSRLV    [[=^^ISA::CPUOpType::ShiftVar]],
        OP_DSRAV    [[=^^ISA::CPUOpType::ShiftVar]],
        OP_MULT     [[=^^ISA::CPUOpType::MulDiv]],
        OP_MULTU    [[=^^ISA::CPUOpType::MulDiv]],
        OP_DIV      [[=^^ISA::CPUOpType::MulDiv]],
        OP_DIVU     [[=^^ISA::CPUOpType::MulDiv]],
        OP_DMULT    [[=^^ISA::CPUOpType::MulDiv]],
        OP_DMULTU   [[=^^ISA::CPUOpType::MulDiv]],
        OP_DDIV     [[=^^ISA::CPUOpType::MulDiv]],
        OP_DDIVU    [[=^^ISA::CPUOpType::MulDiv]],
        OP_ADD      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_ADDU     [[=^^ISA::CPUOpType::ThreeOp]],
        OP_SUB      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_SUBU     [[=^^ISA::CPUOpType::ThreeOp]],
        OP_AND      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_OR       [[=^^ISA::CPUOpType::ThreeOp]],
        OP_XOR      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_NOR      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_RESERVED_14,
        OP_RESERVED_15,
        OP_SLT      [[=^^ISA::CPUOpType::ThreeOp]],
        OP_SLTU     [[=^^ISA::CPUOpType::ThreeOp]],
        OP_DADD     [[=^^ISA::CPUOpType::ThreeOp]],
        OP_DADDU    [[=^^ISA::CPUOpType::ThreeOp]],
        OP_DSUB     [[=^^ISA::CPUOpType::ThreeOp]],
        OP_DSUBU    [[=^^ISA::CPUOpType::ThreeOp]],
        OP_TGE      [[=^^ISA::CPUOpType::Trap]],
        OP_TGEU     [[=^^ISA::CPUOpType::Trap]],
        OP_TLT      [[=^^ISA::CPUOpType::Trap]],
        OP_TLTU     [[=^^ISA::CPUOpType::Trap]],
        OP_TEQ      [[=^^ISA::CPUOpType::Trap]],
        OP_RESERVED_16,
        OP_TNE      [[=^^ISA::CPUOpType::Trap]],
        OP_RESERVED_17,
        OP_DSLL     [[=^^ISA::CPUOpType::Shift]],
        OP_RESERVED_18,
        OP_DSRL     [[=^^ISA::CPUOpType::Shift]],
        OP_DSRA     [[=^^ISA::CPUOpType::Shift]],
        OP_DSLL32   [[=^^ISA::CPUOpType::Shift]],
        OP_RESERVED_19,
        OP_DSRL32   [[=^^ISA::CPUOpType::Shift]],
        OP_DSRA32   [[=^^ISA::CPUOpType::Shift]],
        // REGIMM opcodes
        OP_BLTZ     [[=^^ISA::CPUOpType::Branch1]] = static_cast<uint32_t>(UnifiedOpcodeBase::REGIMM_rt_BASE),
        OP_BGEZ     [[=^^ISA::CPUOpType::Branch1]],
        OP_BLTZL    [[=^^ISA::CPUOpType::Branch1]],
        OP_BGEZL    [[=^^ISA::CPUOpType::Branch1]],
        OP_RESERVED_20,
        OP_RESERVED_21,
        OP_RESERVED_22,
        OP_RESERVED_23,
        OP_TGEI     [[=^^ISA::CPUOpType::TrapImm]],
        OP_TGEIU    [[=^^ISA::CPUOpType::TrapImm]],
        OP_TLTI     [[=^^ISA::CPUOpType::TrapImm]],
        OP_TLTIU    [[=^^ISA::CPUOpType::TrapImm]],
        OP_TEQI     [[=^^ISA::CPUOpType::TrapImm]],
        OP_RESERVED_24,
        OP_TNEI     [[=^^ISA::CPUOpType::TrapImm]],
        OP_RESERVED_25,
        OP_BLTZAL   [[=^^ISA::CPUOpType::Branch1]],
        OP_BGEZAL   [[=^^ISA::CPUOpType::Branch1]],
        OP_BLTZALL  [[=^^ISA::CPUOpType::Branch1]],
        OP_BGEZALL  [[=^^ISA::CPUOpType::Branch1]],
        // COPz RS opcodes
        OP_MFCz     [[=^^ISA::CPUOpType::CP0Move]] = static_cast<uint32_t>(UnifiedOpcodeBase::COPz_rs_BASE),
        OP_DMFCz    [[=^^ISA::CPUOpType::CP0Move]],
        OP_CFCz     [[=^^ISA::CPUOpType::CP0Move]],
        OP_RESERVED_26,
        OP_MTCz     [[=^^ISA::CPUOpType::CP0Move]],
        OP_DMTCz    [[=^^ISA::CPUOpType::CP0Move]],
        OP_CTCz     [[=^^ISA::CPUOpType::CP0Move]],
        OP_RESERVED_27,
        OP_BC       [[=^^ISA::CPUOpType::CP0Move]],
        // COPz RT opcodes
        OP_BCzF     [[=^^ISA::CPUOpType::TypeI_Imm]] = static_cast<uint32_t>(UnifiedOpcodeBase::COPz_rt_BASE),
        OP_BCzT     [[=^^ISA::CPUOpType::TypeI_Imm]],
        OP_BCzFL    [[=^^ISA::CPUOpType::TypeI_Imm]],
        OP_BCzTL    [[=^^ISA::CPUOpType::TypeI_Imm]],
        // CP0 opcodes
        OP_RESERVED_28 = static_cast<uint32_t>(UnifiedOpcodeBase::CP0_BASE),
        OP_TLBR,
        OP_TLBWI,
        OP_RESERVED_29,
        OP_RESERVED_30,
        OP_RESERVED_31,
        OP_TLBWR,
        OP_RESERVED_32,
        OP_TLBP,
        OP_RESERVED_33,
        OP_RESERVED_34,
        OP_RESERVED_35,
        OP_RESERVED_36,
        OP_RESERVED_37,
        OP_RESERVED_38,
        OP_RESERVED_39,
        OP_RESERVED_40,
        OP_RESERVED_41,
        OP_RESERVED_42,
        OP_RESERVED_43,
        OP_RESERVED_44,
        OP_RESERVED_45,
        OP_RESERVED_46,
        OP_RESERVED_47,
        OP_ERET,
    // clang-format on
};

} // namespace Opcodes
